### ISSUE TITLE
warnings in incontext editor

### ISSUE THREAD

**Issue by maciejw** [locize/locize-editor#1]
Can you describe somewhere all warnings displayed on locize.io when using incontext editor?
to give you an example:

warnings.gotoSearchForKeyFromEditor.fallbackToNS 

this displays when I click on a resource. I had other warnings too, and they are not clear at all.

one thing I've noticed also, when I18nextProvider does not have initialLanguage set, location of resource in editor does not work properly, even if I have lng in querystring.

I'm trying to evaluate your service... I think you did not put locize.io sources on github, so locize-editor the closest one  to the source :) 

to give you a background, I'm using react app with based on locize-demo, if its important how exactly I modified demo, let me know.

**Comment by jamuhl** [comment]
1) Hm, you shouldn't get that key but the english value of `The given segment from incontext editor was not found on {{ns}} but we found a possible match on {{foundNS}}`

which means you only "called" clicked a text where we were unable to extract information on which namespace we should lookup that translation -> so we first search in the default namespace, after that we search in all other namespaces -> lucky case it is only found in one -> bad case: text is found in more than one namepace.

To make lookup save you can:
- https://github.com/locize/locize-editor#by-using-cimode-language
- https://github.com/locize/locize-editor#by-adding-attribute-containing-namespace



2) language is taken from qs or i18next.languages[0]: https://github.com/locize/locize-editor/blob/master/src/index.js#L69

3) yes...locize.io is not OSS it's a payed service -> therefor closed source ;). The editor is just a simple small tool to pass information from embedded page to locize.io app
