### ISSUE TITLE
Locize editor with SSR (Next.js)

### ISSUE THREAD

**Issue by GLObus303** [locize/locize-editor#11]
Hey,

I have a problem running inContext locize editor with Next.j.

I am sending the code snippet with it even it's not really important. Problem is initialising the locizeEditor only on front-end which no matter what I do I cant see the small inContext window to start editing.

Do you have any experience with that?

```
const isNode = require('detect-node')
const NextI18Next = require('next-i18next').default
const ICU = require('./icu')
const en = require('i18next-icu/locale-data/en')
const locizeEditor = require('locize-editor')

const icu = new ICU()
icu.addLocaleData(en)
icu.addLocaleData(cs)
icu.addLocaleData(sk)

const use = [icu]

if (isNode) {
  const i18nextNodeLocizeBackend = eval(
    "require('i18next-node-locize-backend')"
  )
  use.push(i18nextNodeLocizeBackend)
} else {
  use.push(locizeEditor)
}

const nextI18Next = new NextI18Next({
  defaultLanguage: 'en',
  defaultNS: 'common',
  use,
  backend: {
    loadPath: '/locales/{{lng}}/{{ns}}.json',
    referenceLng: 'en',
    projectId: 'SOME ID',
    apiKey: 'SOME KEY',
  },
})

module.exports = nextI18Next
```

**Comment by jamuhl** [comment]
Hi there,

Not see an issue with your setup…

Did you open the page appending `?locize=true` in the querystring…?

Best, Jan
locize.com <http://locize.com/>

**Comment by GLObus303** [comment]
Yes I did put the query there, I get this 

```
  var query = window.location.search.substring(1);

ReferenceError: window is not defined
    at getQueryVariable
```

As I said it runs on server-side trying to access window and that's the issue.

**Comment by jamuhl** [comment]
But if i see right you did not add the editor on serverside:

if (isNode) {
const i18nextNodeLocizeBackend = eval(
"require('i18next-node-locize-backend')"
)
use.push(i18nextNodeLocizeBackend)
} else {
use.push(locizeEditor)
}

**Comment by GLObus303** [comment]
```
if (isNode) {
  const i18nextNodeLocizeBackend = eval(
    "require('i18next-node-locize-backend')"
  )
  use.push(i18nextNodeLocizeBackend)
} else {
  const locizeEditor = require('locize-editor')
  use.push(locizeEditor.default)
}
```

The problem was the require, I was trying to do the require through `eval` but it was throwing. Simply moving the `require` to the `false` branch of if fixed the problem.

Thanks!

**Comment by GLObus303** [comment]
The issue now is, that my local translations are not loading, I see only keys. 

```Error: Invalid URI "/locales/en/homepage.json"```

**Comment by jamuhl** [comment]
You will need to use: https://github.com/locize/i18next-locize-backend <https://github.com/locize/i18next-locize-backend> on the clientside (with the options needed)
