### ISSUE TITLE
Add option to toggle the editor

### ISSUE THREAD

**Issue by Vadorequest** [locize/locize-editor#15]
I can't use the editor correctly on part of my app that takes too much space and doesn't allow horizontal scrolling.

Is it possible to add a button to toggle on/off the editor, so that it gets hidden? (somewhere near the "Locize editor On/Off" button would be fine I guess)

---

Also, I recommend renaming the "Locize editor On/Off" button to "Tracking clicks" which is more obvious.
![image](https://user-images.githubusercontent.com/3807458/72100186-70a53000-3322-11ea-903f-cebca717042e.png)

**Comment by jamuhl** [comment]
Not planned currently...

There are options to change style: https://github.com/locize/locize-editor#initialize-with-optional-options or using the mode: "window"

**Comment by Vadorequest** [comment]
Mode "window" will do the trick for now, I had missed it. Thanks!
