### ISSUE TITLE
Can you handle parameterized strings?

### ISSUE THREAD

**Issue by sjatkins** [locize/locize-editor#16]
In our project we have sentences and sentence fragments that take one or more parameters.  The root project is in python.  So we are in basically gettext (standard .po) and jinja2 (web templates) territory.  The parameter markers in .po are of {{paramName}} type.   Mostly they are noun parts of speech.  A few are things like short snippets of text.    When messing about with other translations I had to substitute some string value that would not be translated then programmatically paste the parameter keys needed at run time back in as different languages wanted to take apart and mess with the regular form.

Does locize have something that works well for this?

**Comment by jamuhl** [comment]
Is this question related to the editor or more in general? The editor "just" maps text content in your website to text fragments in the translation management UI - not more.

If your text in source language contains {{param}} and your target language there should be no issue -> How interpolation works depends on the used i18n framework (looks like you already got a system in work). Locize helps with managing the translations...

Might be I don't understand your question completely...could you eventual provide more details?

**Comment by sjatkins** [comment]
Not using editor but existing .po files hopefully via some API bit.  As mentioned {{param}} convention is not handled well by some translations software for some languages such as google translate.  It sounds like you are saying that locize can handle parameter placeholders without messing with them.  Can this be nailed down a bit as to what types of patterns the translation will leave alone and whether they are assumed to be nouns as far as properly flowing a sentence or phrase for the target language?  If I know that much then I can find some way to make it work I believe if there are any cases where the {{param}} form might be otherwise processed by translation.   Some translation software does not respect what is inside {{}} if it is a word known in the target language.  I need something that is guaranteed to be preserved in the translation.

**Comment by jamuhl** [comment]
![image](https://user-images.githubusercontent.com/977772/73162495-31325e00-40ee-11ea-9b37-c3266f5d683c.png)

Just tested: english: `hello {{world}}` -> MT google to de -> `hallo {{world}}` so that should work in most cases
