### ISSUE TITLE
onSaved is only triggered if the corresponding entry is first clicked on the webpage itself.

### ISSUE THREAD

**Issue by jjabba** [locize/locize-editor#17]
I have a react app with locize editor enabled in an iframe and an `onEditorSaved` callback implemented, but it's _not_ called unless click the paragraph I'm changing on my page. 

I.e. if I use the iframe editor itself to find a paragragh and update it, then the `onEditorSaved` callback is not called.

**Comment by jamuhl** [comment]
to have `onEditorSaved` work you have to click...as that's the way the message gets passed to the iframe -> we than can use that message source to send messages back to opener...

But at least if I remember right (not tested) - it should be enough to have clicked it once - as the message source is stored all saves should afterwards trigger the event. Just there has to be one initial message sent (click on text).

**Comment by jjabba** [comment]
I see, it would probably make sense to clarify that in the docs. I spent considerable time trying to debug my callback before I figured out that the 'glitchyness' was because it only works if the text is first clicked.
