### ISSUE TITLE
open on key combo broken

### ISSUE THREAD

**Issue by jjabba** [locize/locize-editor#18]
I configured the editor to open on on ctrl-x:
```
  editor: {
      toggleKeyCode: 24, // x
      toggleKeyModifier: 'ctrlKey',
      ...
```
But pressing that combination only prints this error in the dev-console:

![Screen Shot 2020-05-29 at 6 01 45 PM](https://user-images.githubusercontent.com/1123819/83315703-9c905780-a1d6-11ea-94af-4b833d73ede4.png)

**Comment by adrai** [comment]
toggleKey is used to set die editor interaction to on and of, while the editor is open.
Your error happens, because the editor is not open when you toggle.
with locize-editor@3.0.1 this error will not occur anymore and the editor will open automatically.
