### ISSUE TITLE
Adding a new key should be enabled

### ISSUE THREAD

**Issue by vbilici** [locize/locize-editor#19]
Hello,
It would be nice to have `Add key` option in the editor too. Most of the time I find myself opening locize first adding the key there and going back to the editor. which is not effective and defeats the purpose of the editor.
(Save missing is not an option for us)

Thank you for the awesome product!

**Comment by jamuhl** [comment]
You can do so...just be aware clicking an text element can lead you to two different pages:

a) global search result (as clicking search top right)
b) key in the correct namespace -> as if you select first a namespace

In case b) you can add a key (not in a) as we do not know the namespace there):

![image](https://user-images.githubusercontent.com/977772/85292929-ea7a4180-b49c-11ea-8eda-c0b9242e547d.png)

**Comment by vbilici** [comment]
hmm yes, it only shows the key option when you click on something which has a key already. But I would like to see it when nothing has found.

**Comment by jamuhl** [comment]
Understand...will add it to the backlog...can't make any promise right now on the ETA...as we're currently working on a complete rewrite of the UI I'm not sure it will make it in before we release the new version. But will have to check tomorrow deeper and see if it's easy doable.

**Comment by vbilici** [comment]
Thank you

**Comment by jamuhl** [comment]
@vbilici your feature request should be on production now...

please be aware, if you're filtering the search result and the newly added key/value does not match the criteria it won't show up in the filtered list.

**Comment by vbilici** [comment]
It works, thanks!
