### ISSUE TITLE
Input placeholders

### ISSUE THREAD

**Issue by Flixow** [locize/locize-editor#3]
Hi, could you describe how to deal with input placeholders? For now, clicking on placeholder causes input's focus instead of selecting text in the editor.

**Comment by jamuhl** [comment]
As currently only text nodes can be selected. But i guess we could extend this to input placeholder easily...https://github.com/locize/locize-editor/blob/master/src/index.js#L68

Will need to check this asap.

**Comment by Flixow** [comment]
Yes, looks like easily reachable. Would be great to support placeholders also.

**Comment by jamuhl** [comment]
Should work in locize-editor@1.5.0

Do you use the editor standalone, with i18next (or locizify -> if this we need to update this too)
